using System;
using System.Collections;
using System.Collections.Generic;
using Unity.VisualScripting;
using UnityEngine;
using TMPro;

public class PlaneController : MonoBehaviour
{
    [Header("Plane Stats")] [Tooltip("How much the throttle ramps up of down.")]
    public float throttleIncrement = 0.1f;

    [Tooltip("Maximum engine thrust when at 100% throttle.")]
    public float maxThrust = 200f;

    [Tooltip("How responsive the plane is when rolling, pitching , and yawing")]
    public float ressponsiveness = 10f;

    

    private float throttle;
    private float roll;
    private float pitch;
    private float yaw;

    private float responseModifier
    { get { return (rb.mass / 10f) * ressponsiveness; } }

     Rigidbody rb;
     [SerializeField]  TextMeshProUGUI hud;
     private void Awake()
     {
         rb = GetComponent<Rigidbody>();
     }

     private void HandleInputs()
     {
         roll = Input.GetAxis("Roll");
         pitch = Input.GetAxis("Pitch");
         yaw = Input.GetAxis("Yaw");

         if (Input.GetKey(KeyCode.Space)) throttle += throttleIncrement;
         else if (Input.GetKey(KeyCode.LeftControl)) throttle -= throttleIncrement;
         throttle = Mathf.Clamp(throttle, 0f, 100f);

     }

     private void Update()
     {
         HandleInputs();
         UpdateHUD();
     }

     private void FixedUpdate()
     {
         rb.AddForce(transform.forward * maxThrust *throttle );
         rb.AddTorque(transform.up * yaw * responseModifier);
         rb.AddTorque(transform.right * pitch * responseModifier);
         rb.AddTorque(-transform.forward * roll * responseModifier);
         
         
     }

     private void UpdateHUD()
     {
         hud.text = "Throttle" + throttle.ToString("F0") + "%\n";
         hud.text += "Airspeed:" + (rb.velocity.magnitude * 3.6f).ToString("F0") + "ku/h\n";
         hud.text += "Altitude:" + transform.position.y.ToString("F0") + "m";
     }
}
